version: '3.8'

services:
  go-timezone-api:
    build: .
    container_name: go-timezone-api
    ports:
      - "8081:8080"
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      - go-app-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: GoTimeZoneAPI
    ports:
      - "3306:3306"
    networks:
      - go-app-network
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  go-app-network:
    driver: bridge

volumes:
  mysql-data:


  